name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  amd64:
    runs-on: buildjet-2vcpu-ubuntu-2204
    strategy:
      matrix:
        kernel-version: [ "stable", "4.9" ]
    env:
      CI_KERNEL: ghcr.io/cilium/ci-kernels:${{ matrix.kernel-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends qemu-system-x86

    - run: sudo chmod 0666 /dev/kvm

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  arm64:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    strategy:
      matrix:
        kernel-version: [ "stable" ]
    env:
      CI_KERNEL: ghcr.io/cilium/ci-kernels:${{ matrix.kernel-version }}
      VIMTO_DISABLE_KVM: "true"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends qemu-system-aarch64

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Results
    needs:
    - amd64
    - arm64
    steps:
    - run: exit 1
      if: >-
        ${{
              contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled')
        }}